<?php
$custom = array(
	'groups' => array(
		'fundraising_summary' => array(
			'name' => 'Fundraising_Summary',
			'title' => 'Fundraising Summary',
			'extends' => 'Contact',
			'style' => 'Tab',
			'collapse_display' => '0',
			'help_pre' => '',
			'help_post' => '',
			'weight' => '3',
			'is_active' => '1',
			'is_multiple' => '0',
			'collapse_adv_display' => '0',
		),
  ),
	'fields' => array(
		'total_lifetime' => array(
			'label' => 'Total Lifetime Contributions',
			'data_type' => 'Money',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'total_this_year' => array(
			'label' => 'Total Contributions this Year',
			'data_type' => 'Money',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'total_last_year' => array(
			'label' => 'Total Contributions last Year',
			'data_type' => 'Money',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'amount_last' => array(
			'label' => 'Amount of last contribution',
			'data_type' => 'Money',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'date_last' => array(
			'label' => 'Date of Last Contribution',
			'data_type' => 'Date',
			'html_type' => 'Select Date',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'date_first' => array(
			'label' => 'Date of First Contributions',
			'data_type' => 'Date',
			'html_type' => 'Select Date',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'largest' => array(
			'label' => 'Largest Contribution',
			'data_type' => 'Money',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
		'total_number' => array(
			'label' => 'Total Contributions',
			'data_type' => 'Int',
			'html_type' => 'Text',
			'is_required' => '0',
			'is_searchable' => '1',
			'weight' => '10',
			'is_active' => '1',
			'is_view' => '1',
			'text_length' => '32',
		),
  ),
);
